name: sqfite_database
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  # lib for sqlite saving data
  sqflite: 2.0.0+3
  # grid
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  # format DateTime
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

