name: retrofit_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  retrofit: 2.0.0
  json_serializable: 4.1.3
  dio: 4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: 2.0.5
  retrofit_generator: 2.0.0+3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

